version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: vagalume-db
    restart: always
    environment:
      MYSQL_DATABASE: vagalume
      MYSQL_USER: vagalume
      MYSQL_PASSWORD: vagalume123
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - vagalumenew_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "vagalume", "-pvagalume123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vagalume-backend
    restart: on-failure
    env_file:
      - ./backend/.env.docker
    environment:
      DATABASE_URL: mysql://vagalume:vagalume123@db:3306/vagalume  # Porta interna do container
      PORT: 3001
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    container_name: vagalume-frontend
    restart: always
    environment:
      VITE_API_URL: http://backend:3001/api
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  vagalumenew_db_data: