version: '3.8'

services:
  # MySQL 8.0 Database - Versão Simplificada
  mysql:
    image: mysql:8.0.35-debian
    container_name: vagalume_mysql_simple
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: VagaLume@Root2025!
      MYSQL_DATABASE: vagalume
      MYSQL_USER: vagalume
      MYSQL_PASSWORD: VagaLume@User2025!
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: America/Sao_Paulo
      
    ports:
      - "3306:3306"
    
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=-03:00
      --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      
    networks:
      - vagalume_network
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "vagalume", "-pVagaLume@User2025!"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local

networks:
  vagalume_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16